### PR TITLE
PostTcType no longer present in GHC > 7.8.x

### PR DESCRIPTION
**Pull request by alanz**
I have left the various staged functions in for GHC > 7.8.x, so that it does not break backward compatibility.

### CODE REVIEW

**Comment by alanz** [comment]
Now that cabal 1.22 is out, will you be able to evaluate this?

**Comment by nominolo** [comment]
Thanks, I'll look at this tomorrow.

**Comment by nominolo** [comment]
Done. Released as 0.2.3

**Comment by alanz** [comment]
Thanks

**Pull request closed without merging**
